"""
Convert coarse-grained CSV data to DeepMD-kit training data format

This script reads CSV files generated by get_CGdata_parall.py and converts them
to the DeepMD-kit data format (npy files).
"""

import pandas as pd
import numpy as np
import os
import concurrent.futures
import json
import argparse
import glob
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
from tqdm import tqdm

# =============================================================================
# Configuration Management
# =============================================================================

DEFAULT_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "config.json")


def load_config(config_path: str = None) -> Dict[str, Any]:
    """Load configuration from JSON file"""
    if config_path is None:
        config_path = DEFAULT_CONFIG_PATH

    with open(config_path, 'r') as f:
        config = json.load(f)

    return config


def merge_config_with_args(config: Dict[str, Any], args: argparse.Namespace) -> Dict[str, Any]:
    """Merge command-line arguments with JSON config"""
    if hasattr(args, 'config') and args.config:
        config = load_config(args.config)

    if hasattr(args, 'sim') and args.sim is not None:
        config['simulations'] = [s for s in config['simulations'] if s['name'] == args.sim]

    if hasattr(args, 'temp') and args.temp is not None:
        for sim in config['simulations']:
            if sim['temperatures'] is not None:
                sim['temperatures'] = args.temp

    if hasattr(args, 'base_dir') and args.base_dir:
        config['paths']['cg_data_base_dir'] = args.base_dir

    if hasattr(args, 'output_dir') and args.output_dir:
        config['paths']['output_base_dir'] = args.output_dir

    if hasattr(args, 'workers') and args.workers is not None:
        config['processing']['max_workers'] = args.workers

    return config


# =============================================================================
# Conversion Functions
# =============================================================================

def _ensure_dir(path: str) -> None:
    """Create directory if it doesn't exist"""
    if not os.path.exists(path):
        os.makedirs(path, exist_ok=True)


def find_csv_files(data_dir: str, temp: Optional[int] = None) -> List[Tuple[str, str]]:
    """
    Find CSV file pairs (particles and box_vectors) in data directory

    Args:
        data_dir: Base directory containing CSV files
        temp: Temperature (optional, for path substitution)

    Returns:
        List of (particles_file, box_file) tuples
    """
    if temp is not None:
        data_dir = data_dir.replace("{temp}", str(temp))

    particles_files = glob.glob(os.path.join(data_dir, "*_particles.csv"))

    file_pairs = []
    for particles_file in particles_files:
        basename = particles_file.replace("_particles.csv", "")
        box_file = f"{basename}_box_vectors.csv"

        if os.path.exists(box_file):
            file_pairs.append((particles_file, box_file))

    file_pairs.sort()
    return file_pairs


def _process_one_case(args: Tuple[str, str], conv_config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Process a single CSV file pair to DeepMD format

    Args:
        args: (particles_file, box_file) tuple
        conv_config: Conversion configuration

    Returns:
        Dictionary containing coord, force, energy, box, types arrays
    """
    particles_file, box_file = args

    # Read box data
    df_box = pd.read_csv(box_file)
    box_info = df_box.iloc[:, :-1].values  # Exclude timestep column

    # Check if box varies across timesteps
    if np.unique(box_info, axis=0).shape[0] > 1:
        print(f"Warning: Box varies across timesteps in {os.path.basename(box_file)}")

    # Use the last box (or could use mean/first)
    box = box_info[-1, :].reshape(-1)

    # Read particle data
    df = pd.read_csv(particles_file)

    # Get unique timesteps and process each
    if 'timestep' in df.columns:
        timesteps = df['timestep'].unique()
    else:
        timesteps = [0]  # Single timestep if no timestep column

    all_coords = []
    all_forces = []
    all_energies = []
    all_types = []

    for timestep in timesteps:
        # Filter by timestep
        if timestep != 0:
            df_ts = df[df['timestep'] == timestep]
        else:
            df_ts = df

        # Sort by CG particle ID to ensure consistent ordering
        df_ts = df_ts.sort_values('id')

        # Extract data
        coords = df_ts[['x', 'y', 'z']].values.reshape(-1)
        forces = df_ts[['fx', 'fy', 'fz']].values.reshape(-1)
        energies = df_ts['c_pe'].values.reshape(-1)

        # Get types (ensure types start from 0)
        use_type_column = conv_config.get("use_type_column", True)
        if use_type_column and 'type' in df_ts.columns:
            # Convert types to start from 0
            original_types = df_ts['type'].values.astype(int)
            unique_types = sorted(np.unique(original_types))
            type_mapping = {old: new for new, old in enumerate(unique_types)}
            types = np.array([type_mapping[t] for t in original_types], dtype=int)
        else:
            # Derive from n_atoms (legacy method)
            if 'n_atoms' in df_ts.columns:
                n_atoms = df_ts['n_atoms'].values
                unique_vals = np.unique(n_atoms)
                val_to_type = {val: idx for idx, val in enumerate(sorted(unique_vals))}
                types = np.array([val_to_type.get(val, 0) for val in n_atoms], dtype=int)
            else:
                types = np.zeros(len(df_ts), dtype=int)

        all_coords.append(coords)
        all_forces.append(forces)
        all_energies.append(energies)
        all_types.append(types)

    return {
        'coords': np.array(all_coords),
        'forces': np.array(all_forces),
        'energies': np.array(all_energies),
        'box': box,
        'types': np.array(all_types),
        'n_frames': len(all_coords),
        'n_particles': len(df['id'].unique()) if 'id' in df.columns else len(df_ts)
    }


def process_simulation(sim_config: Dict[str, Any],
                      paths_config: Dict[str, Any],
                      conv_config: Dict[str, Any],
                      proc_config: Dict[str, Any],
                      output_config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Process a single simulation type

    Args:
        sim_config: Simulation configuration
        paths_config: Path configuration
        conv_config: Conversion configuration
        proc_config: Processing configuration
        output_config: Output configuration

    Returns:
        Statistics dictionary
    """
    if not sim_config.get("enabled", True):
        return {
            'name': sim_config['name'],
            'enabled': False,
            'total_files': 0,
            'success': 0,
            'failed': 0,
            'errors': []
        }

    stats = {
        'name': sim_config['name'],
        'enabled': True,
        'total_files': 0,
        'success': 0,
        'failed': 0,
        'total_frames': 0,
        'total_particles': 0,
        'errors': []
    }

    temperatures = sim_config.get('temperatures')
    if temperatures is None:
        temperatures = [None]

    data_subdir = sim_config.get('data_subdir', '')
    out_subdir = sim_config.get('output_subdir', '')

    for temp in temperatures:
        temp_str = f"{temp}K" if temp is not None else "N/A"

        # Build paths
        if temp is not None:
            data_dir = os.path.join(paths_config['cg_data_base_dir'],
                                    data_subdir.replace("{temp}", str(temp)))
            out_dir = os.path.join(paths_config['output_base_dir'],
                                    out_subdir.replace("{temp}", str(temp)))
        else:
            data_dir = os.path.join(paths_config['cg_data_base_dir'], data_subdir)
            out_dir = os.path.join(paths_config['output_base_dir'], out_subdir)

        if not os.path.exists(data_dir):
            stats['errors'].append(f"Data directory does not exist: {data_dir}")
            continue

        # Find CSV files
        file_pairs = find_csv_files(data_dir, temp)

        if not file_pairs:
            continue

        stats['total_files'] += len(file_pairs)

        # Create output directory
        if proc_config.get('create_output_dirs', True):
            _ensure_dir(out_dir)

        # Process files
        all_coords = []
        all_forces = []
        all_energies = []
        all_box = []
        all_types = []

        max_workers = proc_config.get('max_workers')
        if max_workers is None:
            max_workers = os.cpu_count() or 1

        tasks = [(fp[0], fp[1]) for fp in file_pairs]

        if proc_config.get('parallel', True):
            with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
                # Use submit and as_completed for better error handling
                future_to_task = {executor.submit(_process_one_case, task, conv_config): task for task in tasks}
                with tqdm(total=len(tasks), desc=f"  {sim_config['name']} {temp_str}",
                          unit='file', ncols=100, leave=False) as pbar:
                    for future in concurrent.futures.as_completed(future_to_task):
                        task = future_to_task[future]
                        try:
                            result = future.result()
                            all_coords.append(result['coords'])
                            all_forces.append(result['forces'])
                            all_energies.append(result['energies'])
                            all_box.append(result['box'])
                            all_types.append(result['types'])
                            stats['success'] += 1
                            stats['total_frames'] += result['n_frames']
                            stats['total_particles'] += result['n_particles']
                        except Exception as e:
                            stats['failed'] += 1
                            stats['errors'].append(f"{os.path.basename(task[0])}: {str(e)}")
                        pbar.update(1)
        else:
            with tqdm(total=len(tasks), desc=f"  {sim_config['name']} {temp_str}",
                      unit='file', ncols=100, leave=False) as pbar:
                for task in tasks:
                    try:
                        result = _process_one_case(task, conv_config)
                        all_coords.append(result['coords'])
                        all_forces.append(result['forces'])
                        all_energies.append(result['energies'])
                        all_box.append(result['box'])
                        all_types.append(result['types'])
                        stats['success'] += 1
                        stats['total_frames'] += result['n_frames']
                        stats['total_particles'] += result['n_particles']
                    except Exception as e:
                        stats['failed'] += 1
                        stats['errors'].append(f"{os.path.basename(task[0])}: {str(e)}")
                    pbar.update(1)

        if not all_coords:
            continue

        # Convert to numpy arrays
        all_coords = np.concatenate(all_coords, axis=0)
        all_forces = np.concatenate(all_forces, axis=0)
        all_energies = np.concatenate(all_energies, axis=0)
        all_box = np.array(all_box)
        all_types = np.concatenate(all_types, axis=0)

        # Validate data
        if len(all_coords) == 0 or len(all_types) == 0:
            stats['errors'].append("Empty data after concatenation")
            continue

        # Calculate total energy per frame
        if all_energies.ndim == 1:
            # Single frame per case
            total_energy = all_energies
        else:
            total_energy = np.sum(all_energies, axis=1)

        # Write output files
        _ensure_dir(out_dir)
        _ensure_dir(os.path.join(out_dir, "set.000"))

        if output_config.get("save_raw_files", True):
            np.savetxt(os.path.join(out_dir, "box.raw"), all_box, fmt='%.8f', delimiter=' ')
            np.savetxt(os.path.join(out_dir, "coord.raw"), all_coords, fmt='%.8f', delimiter=' ')
            np.savetxt(os.path.join(out_dir, "force.raw"), all_forces, fmt='%.8f', delimiter=' ')
            np.savetxt(os.path.join(out_dir, "atom_ener.raw"), all_energies, fmt='%.8f', delimiter=' ')
            np.savetxt(os.path.join(out_dir, "energy.raw"), total_energy, fmt='%.8f', delimiter=' ')

            # Write type.raw (use types from first frame)
            # all_types shape is (n_frames, n_particles)
            # We need the types for just one frame (all frames have same types)
            try:
                if all_types.ndim > 1:
                    # Multiple frames - use first frame's types
                    first_frame_types = all_types[0, :]
                elif all_types.ndim == 1:
                    # Single frame - use all types
                    first_frame_types = all_types
                else:
                    # Unexpected shape - use first n_particles types
                    first_frame_types = all_types.flatten()[:all_coords.shape[1] // 3] if all_coords.ndim > 1 else all_types.flatten()

                with open(os.path.join(out_dir, "type.raw"), 'w') as f:
                    f.write(' '.join(map(str, first_frame_types.tolist())) + "\n")

                # Write type_map.raw (CG1 CG2 CG3 ...)
                # Get unique CG types
                unique_types = np.unique(first_frame_types)
                type_map_str = ' '.join([f"CG{int(t)}" for t in sorted(unique_types)])
                with open(os.path.join(out_dir, "type_map.raw"), 'w') as f:
                    f.write(type_map_str + "\n")
            except Exception as e:
                stats['errors'].append(f"Error writing type.raw: {e}")
                # Write default types as fallback
                n_particles = all_coords.shape[1] // 3 if all_coords.ndim > 1 else len(all_types)
                default_types = np.ones(n_particles, dtype=int)
                with open(os.path.join(out_dir, "type.raw"), 'w') as f:
                    f.write(' '.join(map(str, default_types.tolist())) + "\n")

                # Write default type_map.raw
                with open(os.path.join(out_dir, "type_map.raw"), 'w') as f:
                    f.write("CG1\n")

        if output_config.get("save_npy_files", True):
            num_groups = conv_config.get("num_groups", 1)
            groups = max(1, num_groups)

            splits_coords = np.array_split(all_coords, groups, axis=0)
            splits_forces = np.array_split(all_forces, groups, axis=0)
            splits_ener = np.array_split(all_energies, groups, axis=0)
            splits_box = np.array_split(all_box, groups, axis=0)
            splits_total = np.array_split(total_energy, groups, axis=0)

            for g in range(groups):
                set_dir = os.path.join(out_dir, f"set.{g:03d}")
                _ensure_dir(set_dir)

                np.save(os.path.join(set_dir, "box.npy"), splits_box[g])
                np.save(os.path.join(set_dir, "coord.npy"), splits_coords[g])
                np.save(os.path.join(set_dir, "force.npy"), splits_forces[g])
                np.save(os.path.join(set_dir, "atom_ener.npy"), splits_ener[g])
                np.save(os.path.join(set_dir, "energy.npy"), splits_total[g])

    return stats


# =============================================================================
# Main Function
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description='Convert CG CSV data to DeepMD-kit training format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use default config.json
  python trans_CGnpy_parall.py

  # Use custom config file
  python trans_CGnpy_parall.py --config my_config.json

  # Process only 1-npt simulations
  python trans_CGnpy_parall.py --sim 1-npt

  # Process specific temperatures
  python trans_CGnpy_parall.py --temp 200 300

  # Override base directory
  python trans_CGnpy_parall.py --base-dir /path/to/cg_data

  # Set number of workers
  python trans_CGnpy_parall.py --workers 4
        """
    )

    parser.add_argument('--config', '-c', type=str, default=None,
                        help='Path to JSON configuration file (default: config.json)')
    parser.add_argument('--sim', type=str, default=None,
                        choices=['1-npt', '2-nvt', '3-upT', '4-dnT'],
                        help='Process only this simulation type (overrides config)')
    parser.add_argument('--temp', type=int, nargs='+', default=None,
                        help='Temperature(s) to process (overrides config)')
    parser.add_argument('--base-dir', type=str, default=None,
                        help='Base directory for CG data (overrides config)')
    parser.add_argument('--output-dir', type=str, default=None,
                        help='Output base directory (overrides config)')
    parser.add_argument('--workers', '-w', type=int, default=None,
                        help='Number of parallel workers (overrides config)')

    args = parser.parse_args()

    # Load configuration
    try:
        config = load_config(args.config)
    except Exception as e:
        print(f"Error loading configuration: {e}")
        return 1

    # Merge with command-line arguments
    config = merge_config_with_args(config, args)

    # Extract config sections
    paths_config = config['paths']
    conv_config = config['conversion']
    proc_config = config['processing']
    output_config = config['output']

    # Print header
    print(f"\n{'='*60}")
    print("CSV TO DEEPMD-KIT FORMAT CONVERSION")
    print(f"{'='*60}")
    print(f"CG data directory: {paths_config['cg_data_base_dir']}")
    print(f"Output directory: {paths_config['output_base_dir']}")
    print(f"Use type column: {conv_config.get('use_type_column', True)}")
    print(f"Number of groups: {conv_config.get('num_groups', 1)}")
    print(f"{'='*60}\n")

    # Process each simulation
    all_stats = []
    enabled_sims = [s for s in config['simulations'] if s.get("enabled", True)]

    for sim_config in enabled_sims:
        stats = process_simulation(
            sim_config, paths_config, conv_config, proc_config, output_config
        )
        all_stats.append(stats)

    # Print final summary
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")

    total_files = 0
    total_success = 0
    total_failed = 0
    total_frames = 0
    total_particles = 0

    for stats in all_stats:
        if not stats['enabled']:
            continue

        total_files += stats['total_files']
        total_success += stats['success']
        total_failed += stats['failed']
        total_frames += stats['total_frames']
        total_particles += stats['total_particles']

        if stats['total_files'] > 0:
            print(f"\n{stats['name']}:")
            print(f"  Files: {stats['success']}/{stats['total_files']} processed")
            if stats['failed'] > 0:
                print(f"  Failed: {stats['failed']}")
            if stats['total_frames'] > 0:
                print(f"  Frames: {stats['total_frames']:,}")
            if stats['total_particles'] > 0:
                print(f"  Particles: {stats['total_particles']:,}")

    print(f"\n{'='*60}")
    print("TOTAL:")
    print(f"  Files: {total_success}/{total_files} processed")
    if total_failed > 0:
        print(f"  Failed: {total_failed}")
    if total_frames > 0:
        print(f"  Frames: {total_frames:,}")
    if total_particles > 0:
        print(f"  Particles: {total_particles:,}")
    print(f"{'='*60}\n")

    # Print errors if any
    has_errors = any(len(s['errors']) > 0 for s in all_stats)
    if has_errors:
        print("Errors:")
        for stats in all_stats:
            for err in stats['errors']:
                print(f"  [{stats['name']}] {err}")
        print()

    return 0 if total_failed == 0 else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
